### ISSUE TITLE
feature: Location(err)string 

### ISSUE THREAD

**Issue by rand99** [pkg/errors#10]
really nice project! 
I only miss one thing while using logrus

```go
	log.WithFields(logrus.Fields{
		"code": "HandlerCheckBla",
		"user_id": user_id,
		"last_check": last_check,
                 "err_location":  errors.Location(err),   // <-------
	}).Error(err)
```

could you please add something like ...

```go
func Location( err error) string  {
	str := ""
	for err != nil {
		location, ok := err.(locationer)
		if ok {
			file, line := location.Location()
			str += fmt.Sprintf("%s:%d: \n", file, line)
		}
		cause, ok := err.(causer)
		if !ok {
			return str
			break
		}
		err = cause.Cause()
	}
	return ""
 #}
```

to errors.go ... ? 👍

**Comment by davecheney** [comment]
Thank you for raising this issue. I'm hesitant to add this helper for a few
reasons.

The first is I'm not sure how often it'll be used, itll certainly not be as
common as Wrap and Cause.

The second is the sample code you wrote doesn't do what I think you think
it does, your sample will print the location of the topmost wrapped error,
not the underlying cause. Printing the top of the error stack doesn't seem
as useful as printing the bottom.

Also, if you wrote something like Location(Cause(err)) that would return a
blank line if the underlying cause of the error did not have a location,
which I think is quite common.

I think he location interface is probably most useful for printing the
whole error stack, not for ad-hoc investigation.

Thanks

Dave

**Comment by rand99** [comment]
I understand. I've just noticed that the returned line number was wrong plus faulty-reasoning^2 (14 hours, time for sleep)
Still kinda need the file and line numbers on my log-server
So I'll just go with the modified Fprint to pass it to logrus.

Thanks Dave

```go
func Stack( err error) string {
	str := ""
	for err != nil {
		location, ok := err.(locationer)
		if ok {
			file, line := location.Location()
			str += fmt.Sprintf("%s:%d: ", file, line)
		}
		switch err := err.(type) {
		case *e:
			str += fmt.Sprintln(err.message)
		default:
			str += fmt.Sprintln(err.Error())
		}

		cause, ok := err.(causer)
		if !ok {
			return str
		}
		err = cause.Cause()
	}
	return ""
}
```

**Comment by davecheney** [comment]
Don't forget errors.Fprint which will print a formatted stack of errors to an io.Writer
