### ISSUE TITLE
Export stack?

### ISSUE THREAD

**Issue by willfaught** [pkg/errors#101]
Exporting stack would let you get the nice stack formatting that you get with actual errors.

**Comment by davecheney** [comment]
I'm not sure what you mean? That's what this package does, you can use the
%+v verb, our you can assert that the error implements a StackTrace method
and call that

https://godoc.org/github.com/pkg/errors#example-package--StackTrace

**Comment by willfaught** [comment]
Right, but you need to have an error to get it, right? Maybe that's outside the scope of this package...

**Comment by davecheney** [comment]
This might be a better fit, https://godoc.org/github.com/go-stack/stack

**Comment by willfaught** [comment]
Thanks. I couldn't find that again. Works for me!
