### ISSUE TITLE
Proposal: How to use Type system to force use of decorated errors

### ISSUE THREAD

**Issue by j16r** [pkg/errors#103]
First off: thanks for a really great library and hope this is the right place for this.

Within the confines of my particular application I'd really like to make sure that *ALL* errors have been decorated with a stack trace. I feel like the best way to do this would be with the type system, perhaps:

```go
func MyRecordCreationFunction(some args...) (record, errors.ErrorWithStack) {
   record, err := orm.CreateObj("...")
   if err != nil {
     return nil, errors.WithStack(err)
   }

   err = record.hydrate()
   if err != nil {
     return nil, err // <- fails to compile, type error does not implement method StackTrace() ...
   }

   return record, nil
}
```

Unfortunately this is quite challenging with the types that this package decides to export right now. Is there another way to achieve this? Or is this worthy of a PR?

Thanks for your time.

**Comment by davecheney** [comment]
Is the problem that record.Hydrate() returns error, not a type that exports
Stack trace?

**Comment by j16r** [comment]
@davecheney that's right, my app is made up of code I've written - where I can always use this library and other libraries like `sqlx` where I have to wrap things.

**Comment by davecheney** [comment]
I'm not quite sure what you want to change in the errors package, the code
you showed worked fine wrt errors.WithStack.

**Comment by j16r** [comment]
Ahh, that's the point - excuse my edit. I want it to fail! I want to reject any error that hasn't captured a stack trace.

**Comment by aviau** [comment]
Any news on did? Did you find a solution?

I would love to use the type system to assure me that my program returns decorated errors all over.

**Comment by aviau** [comment]
I guess that it could suffice to define something like this in my code:

```golang
type ErrorCauser interface {
    Error() string
    Cause() error
}
```

Then function signatures can look like:
```golang
func doThing() errorCauser
```

**Comment by aviau** [comment]
I have implemented the best solution that I could think of in a new package:
 - https://github.com/aviau/errors

Feel free to comment. It is mostly compatible with pkg/errors.

**Comment by j16r** [comment]
Closing, if you want this use https://github.com/aviau/errors !
