### ISSUE TITLE
Cause only returns the last item in the error chain

### ISSUE THREAD

**Issue by borismattijssen** [pkg/errors#104]
When I create a chain of errors (using `errors.Wrap`) and try to peel off the outer error (using `errors.Cause`) it will traverse all the way to the last error in the error chain.
For example:
```
err := errors.Wrap(errors.Wrap(errors.Wrap(errors.New("error1"), "error2"), "error3"), "error4")
fmt.Println(errors.Cause(err))
//output: "error1", expected output: "error3: error2: error1"
```

To me this looks like unexpected behaviour.

**Comment by davecheney** [comment]
This is working as intended. The name may be a little misleading, but we
cannot change it now. errors.Cause returns the innermost error, the one
that does not implement Cause itself.

**Comment by borismattijssen** [comment]
Ok. Are there any helper functions that allow me to "peel off" the outer error?

**Comment by davecheney** [comment]
type causer interface {
        Cause() error
}

if err2, ok := err.(causer); ok {
        err = err2
}

**Comment by borismattijssen** [comment]
Fair enough, thanks 👍
