### ISSUE TITLE
Proposal: Add the concept of ErrorHandler

### ISSUE THREAD

**Issue by sagikazarmark** [pkg/errors#119]
In some cases I met the need for *something* which is able to log/report an error in a library without actually returning it to the caller.

A typical example is when you loop through a list of elements and call a method on them which might return an error without causing the application to get into an erroneous state:

``` go
errorHandler := ...
handlers := ...

func Shutdown() {
	// Try recovering from panic first
	err := errors.Recover(recover())
	if err != nil {
		errorHandler.Handle(err)
	}

	// Loop through all the handlers and call them
	// Log any errors that may occur
	for _, handler := range handlers {
		err := handler()
		if err != nil {
			errorHandler.Handle(err)
		}
	}
}
```

In this case the error handler looks like this:

``` go
// Handler is responsible for handling an error.
//
// This interface allows libraries to decouple from logging solutions.
// In most cases the implementation will provide some log functionalities though.
type Handler interface {
	Handle(err error)
}
```

An obvious advantage is that one does not have to rely on a leveled-logger solution in a library for example.

Looking at libraries like Logrus, they often contain hooks for well-known error/exception tracking systems like Airbrake and Bugsnag. Personally I think that it's not really a good practice to report errors like this. With the error handler concept Airbrake, Bugsnag, etc come to the same level as logging as they all become error handlers.

Looking forward to hear some opinion.

**Comment by davecheney** [comment]
I don't see why this needs to be part of this package. From what you've
described, it's only an interface declaration.

**Comment by sagikazarmark** [comment]
Well, someone may consider this package as a sane extension of the standard library error package in which case I don't see a reason against having such "recommendations" in this package. Anyway, it's just a proposal, no hard feelings if you don't see it fit here.

**Comment by davecheney** [comment]
It's not clear to me how this would be used. It's just an interface
declaration, and people can just declare their own in their own, and avoid
the import dependency on this package​.

**Comment by sagikazarmark** [comment]
Sure thing, thanks for your answer though.
