### ISSUE TITLE
Proposal: errors.Const("Example")

### ISSUE THREAD

**Issue by puellanivis** [pkg/errors#126]
Reference: https://dave.cheney.net/2016/04/07/constant-errors

```
type Const string

func (c Const) Error() string {
  return string(c)
}
```

This would allow (in cases where a sentinel error is a good choice) to use: `const EOF = errors.Const("EOF")`

For cases, where, like io.EOF, the value is not really an error, but rather a condition that need be commonly checked for. Yes, io.EOF isn’t going to change anytime soon, but at least future libraries could provide these out-of-bound-condition sentinel values in a better and safer way.

**Comment by burdiyan** [comment]
I was just about submitting the same issue. +1

**Comment by burdiyan** [comment]
Not sure thought whether should it be called Const or anything else. But the pattern itself will be quite great to have.

**Comment by davecheney** [comment]
To give some feedback. Thank you for suggesting this, I agree it would be a
useful tool to have, but I'm concerned it would legitimise the idea of
checking errors by value.

The post I wrote on constant errors had more on this, but in the set of
exported error values in the stdlib there are few, possibly only a handful
of sentinel errors.

I'm concerned about adding this feature as it may distract from the
narrative that go programmers shouldnt use sentinel errors, instead they
should be asserting for type or behaviour when checking errors.

**Comment by burdiyan** [comment]
@davecheney I knew you were going to say that very thing :) And I would probably agree on that. Although, I believe people are going to use sentinel errors anyway using global vars, and maybe giving them an easy option to at least making these errors constant will make their lives a little bit better.

**Comment by davecheney** [comment]
By the same argument, if there are tools to make it easy to create sentinel
error values, then developers will continue to do so.

**Comment by puellanivis** [comment]
Indeed. It's a stinky situation. If you fix Sentinel errors in general, then people will use them, and not use better go idioms. :(

Curious, the only winning move is not to play. :(

**Comment by davecheney** [comment]
Thanks but no thanks. Closing based on my comments on https://github.com/pkg/errors/issues/126#issuecomment-324170015
