### ISSUE TITLE
Add errors.Errorf method

### ISSUE THREAD

**Issue by scorredoira** [pkg/errors#13]
Hi, would it make sense to have a Newf method to avoid having to write this?

     errors.New(fmt.Sprintf("something %v", x))

If you think it does I can make a PR.

Thank you

**Comment by davecheney** [comment]
probably errors.Errorf would be better.

**Comment by scorredoira** [comment]
yes, much better, Newf didn't sound right :)

**Comment by scorredoira** [comment]
I saw the note. So how should I do it, amend to the last commit, two commits or create a new PR? Also, I didn't think it was worth it to add a test for such a simple addition. Is it OK?

**Comment by davecheney** [comment]
> I saw the note. So how should I do it, amend to the last commit, two commits or create a new PR? Also, I didn't think it was worth it to add a test for such a simple addition. Is it OK?

Just amend the existing PR.

Please add a test, everything needs a test to ensure it continues to work. Adding an example means we get documentation for free.
