### ISSUE TITLE
Inconsistency between documentation and code

### ISSUE THREAD

**Issue by ihrwein** [pkg/errors#136]
I found a little inconsistency between the documentation and the actual implementation.

The documentation says that if a `Frame` is formatted with `%+s` the produced string is the "path of source file relative to the compile time GOPATH". [link](https://github.com/pkg/errors/blob/master/stack.go#L49)

However, according to the [implementation](https://github.com/pkg/errors/blob/master/stack.go#L62) it also contains the function name.

Is this difference intended or not?

**Comment by davecheney** [comment]
Probably both, +s turns on printing the file name _as well as_ the function
name.

Do you want to send a documentation PR?

**Comment by ihrwein** [comment]
Of course yes. Just let me raise a question before the PR.

Do you want to support printing only the "path of source file relative to the compile time GOPATH" with a flag? I need that information and if we keep the current behavior, I'll need to split the string along "\n\t" to get the path component. Is that separator sequence part of the public API?

**Comment by davecheney** [comment]
Just document the current behaviour. We probably cannot change the output
at this point.
