### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by walle** [pkg/errors#152]
Testing out [vgo](https://research.swtch.com/vgo) I noticed that this package's last release is v0.8.0 from `2016-09-29 03:48`. This is the changes that have happened since then https://github.com/pkg/errors/compare/v0.8.0...master.

Does it make sense to do a new release, at least a patch version if the changes are small, to be able to use the latest code with vgo? Without pinning to a commit that is.

**Comment by ebati** [comment]
Having a new release would be great, since v0.8.0 cannot pass test with go1.11.
> ./bench_test.go:26:6: toperr declared but not used
> vet: typecheck failures

This is fixed at tip as toperr is replaced with GlobalE.

Related go1.11 release note:
>Since Go 1.10, the go test command runs go vet on the package being tested, to identify problems before running the test. Since vet typechecks the code with go/types before running, tests that do not typecheck will now fail. In particular, tests that contain an unused variable inside a closure compiled with Go 1.10, because the Go compiler incorrectly accepted them (Issue #3059), but will now fail, since go/types correctly reports an "unused variable" error in this case.

**Comment by stjohnjohnson** [comment]
@davecheney any chance we could get a `v0.9.0` release cut?

**Comment by dcormier** [comment]
It would be nice to get a new release cut so that `WithMessagef` is available without having to force `dep` to use `master` instead of the last release.

**Comment by davecheney** [comment]
I'm working on it. Sorry I don't have an ETA.

**Comment by davecheney** [comment]
v0.8.1 has been tagged.
