### ISSUE TITLE
Consider LIFO printing for %+v (I'll implement a PR if this is ok)

### ISSUE THREAD

**Issue by mitranim** [pkg/errors#157]
In `causer` errors, as currently implemented, `%+v` uses FIFO ordering, while other modes and `Error()` use LIFO ordering. Consider:

```go
cause := errors.New("database connection lost")
effect := errors.WithMessage(cause, "failed to query session")

// (1)
fmt.Println(effect)

// (2)
fmt.Printf("%+v\n", effect)
```

(1) makes perfect sense:

```
failed to query session: database connection lost
```

(2), on the other hand:

```
database connection lost
main.main
  /<path>/test.go:10
runtime.main
  /<go path>/libexec/src/runtime/proc.go:198
runtime.goexit
  /<go path>/libexec/src/runtime/asm_amd64.s:2361
failed to query session
```

I find this really weird and inconvenient to read. The stacktrace itself is LIFO; following the same order for error messages would make the whole thing a lot more sensible. It should look roughly like this:

```
failed to query session
database connection lost
main.main
  /<path>/test.go:10
runtime.main
  /<go path>/libexec/src/runtime/proc.go:198
runtime.goexit
  /<go path>/libexec/src/runtime/asm_amd64.s:2361
```

I'm willing to do a PR is we can agree on this.

Thanks for the package btw. It has probably saved me hours of debugging already. 😄

**Comment by davecheney** [comment]
I'm sorry it's not possible to change the ordering of output at this stage and I won't be adding a flag to make this user configurable.

I'm trying to tidy this package up for a 1.0.0 release which will lock in the current behaviour.
