### ISSUE TITLE
Stack trace incorrect in go 1.12

### ISSUE THREAD

**Issue by uberbo** [pkg/errors#180]
Simplest way to reproduce:
<pre>
package main

import (
	"fmt"
	"github.com/pkg/errors"
)

func main() {
	fmt.Printf("%+v\n", errors.New("fail fast"))
}
</pre>

#### Output:
Wrong file name for main.main and includes skipPleaseUseCallersFrames:
<pre>
fail fast
main.main
	/gocode/src/github.com/pkg/errors/errors.go:104
runtime.skipPleaseUseCallersFrames
	/sdk/go1.12beta1/src/runtime/asm.s:40
runtime.main
	/sdk/go1.12beta1/src/runtime/proc.go:200
runtime.goexit
	/sdk/go1.12beta1/src/runtime/asm_amd64.s:1337
</pre>
Using
<pre>
go version go1.12beta1 darwin/amd64
</pre>

#### Expected output
<pre>
fail fast
main.main
	/gocode/src/playground/go12betapkgerrors/main.go:9
runtime.main
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/proc.go:201
runtime.goexit
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/asm_amd64.s:1333
</pre>

Related: https://github.com/golang/go/issues/29526#issuecomment-451117761

**Comment by davecheney** [comment]
Thank you for raising this issue. I'm hoping to have this fixed by the time
1.12 is released.

**Comment by davecheney** [comment]
Fixed in #183
