### ISSUE TITLE
PROPOSAL: Change the printing order of the Error() method

### ISSUE THREAD

**Issue by amariampolskiy** [pkg/errors#201]
Right now it prints in format msg: cause and i think it should be in reverse order. After all, msg is the clarification of the cause error, so it's only logical for it to go last, not first.

**Comment by davecheney** [comment]
I’m sorry, we can’t change the format now. However undesirable people are parsing it.

**Comment by amariampolskiy** [comment]
Perhaps some sort of config for printing order? With default value being current method. That would make the changes backwards compatible

**Comment by davecheney** [comment]
I’m sorry but no. With the inclusion of any errors package in Go 1.13 you should send your feature requests to the go team.

**Comment by amariampolskiy** [comment]
Got it, then i'm closing the issue
