### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by shawnps-sigsci** [pkg/errors#209]
@davecheney it seems like there are some performance enhancements in master that aren't in a tagged release - any way we could get a `v0.8.2` tag? 😄

**Comment by thaJeztah** [comment]
Looks like it would be `v0.9.0`; from the [`v0.8.1` release notes](https://github.com/pkg/errors/releases/tag/v0.8.1); 

> pkg/errors 0.8.1 is a bug fix release for errors 0.8.0. It will be the last version to support Go 1.8 and below. pkg/errors 0.9 and above will require Go 1.9 for the new runtime.CallersFrames API.

**Comment by lwaddicor** [comment]
With the latest changes to support go 1.13 error chains it would be really good to get a release with this in it!

https://github.com/pkg/errors/commit/7f95ac13edff643b8ce5398b6ccab125f8a20c1a

**Comment by aperezg** [comment]
Yes we're working on it, we want to publish a new release when the library was completely compatible with the new go1.13 errors, we will try that was soon.

**Comment by lwaddicor** [comment]
That's good to know, thank you!

**Comment by edkolev** [comment]
Seems like 1.13 errors are completely covered now that https://github.com/pkg/errors/commit/49f8f617296114c890ae0b7ac18c5953d2b1ca0f is in master

**Comment by aperezg** [comment]
The new release is finally here: https://github.com/pkg/errors/releases/tag/v0.9.0

**Comment by lwaddicor** [comment]
> The new release is finally here: https://github.com/pkg/errors/releases/tag/v0.9.0

Thank you, you wonderful folk!
