### ISSUE TITLE
[feature] errors.Unwrap

### ISSUE THREAD

**Issue by davecheney** [pkg/errors#21]
We have `Wrap` which takes an `error` and returns a new `error` which supports `Cause` and will return the original error.

This issue is to discuss adding a complement to `Wrap`, `Unwrap` is specified as follows

     // Unwrap reverses the Wrap process above, returning the direct cause
     // of the error. If the error does not support Cause, or the error is nil, the 
     // error value is returned unmodified.
     func Unwrap(err error) error 

For discussion
- [ ] Is this useful enough to justify adding to the package, vs doing this with a switch statement ?
- [ ] Is the API appropriate, specifically in the case of an error which does not have a cause.

See also #18

**Comment by davecheney** [comment]
I'm going to close this as I think it's going in the wrong direction. 

The original design of this errors package mirror'd Juju's which requires callers to manually wrap each level of error return to record a stack trace. Apart from this being incomplete and verbose, on reflection I think the _natural_ stack trace recorded at the point the error happens is probably good enough (tm) for most use cases. In the cases where they are not, errors.Wrap allows the caller to add additional context to the error path. 

In either cases the printing of this stack detail, including the nested stacks now possible since #27 makes this method less useful.

**Comment by jaekwon** [comment]
Related: https://github.com/pkg/errors/issues/144

**Comment by powerman** [comment]
@davecheney Maybe it's worth to reconsider this now? It may be very useful to provide Unwrap() compatible with stdlib's errors, to make it easier to migrate existing codebase from pkg/errors to stdlib's errors or use both in parallel.

I mean, I'd like to replace `errors.Cause()` with `errors.Is()` in existing code, but this require pkg/errors to support Unwrap().
