### ISSUE TITLE
func Is() does not works with errors.Wrap or errors.Wrapf

### ISSUE THREAD

**Issue by waichee** [pkg/errors#218]
Checking of a error type in the error chain only works for errors wrapped with `fmt.Errorf`
`fmt.Errorf("some %w", err)`

Errors wrapped with `errors.Wrap(err, "some stuff")` does not work when being checked with

```
var specialError = errors.New("defined type error")

err1 := fmt.Errorf("some %w", specialError)

err2 := errors.Wrap(specialError, "some stuff")

// this works
errors.Is(err1, specialError) 

// this doesnt work
errors.Is(err2, specialError) 
```

**Comment by puellanivis** [comment]
Which version of the `errors` package are you using? If you are not using the latest master branch (so, you’re using `0.8.1` or any other release) then the package is incompatible with the standard errors library.

We are working on cutting a new release that will be compatible with standard errors package expansions. But it’s kind of slow going as everything is done by volunteers.

**Comment by waichee** [comment]
ah master branch works!
thanks

**Comment by aperezg** [comment]
Now also in a new [v0.9.0](https://github.com/pkg/errors/releases/tag/v0.9.0) release
