### ISSUE TITLE
respect -trimpath build flag

### ISSUE THREAD

**Issue by axetroy** [pkg/errors#222]
Remove the $GOPATH path when `go build`

But doesn't seem to work for this library

```shell
go build -gcflags=-trimpath=$GOPATH -asmflags=-trimpath=$GOPATH xxxxxxx
```

**Comment by davecheney** [comment]
What doesn’t work? 

What did you do?

What did you expect to see?

What did you see instead?

**Comment by axetroy** [comment]
@davecheney 
`-trimpath` flag will delete the specified path in the stack information

This ensures that the stack information does not expose the path

But it seems that the stack information generated using `pkg/errors` still contains these paths

**Comment by davecheney** [comment]
I don't think I can help you. `-trimpath` is handled by the compiler. This package doesn't have access to this flag at runtime. I suggest raising an issue on golang/go if `-trimpath` does not work.
