### ISSUE TITLE
panic: values with embedded slices uncomparable errors

### ISSUE THREAD

**Issue by stevvooe** [pkg/errors#29]
Please see the stack trace here: https://travis-ci.org/opencontainers/image-spec/builds/132403826, described by opencontainers/image-spec#84.

Looks like pkg/errors#27 introduced or exposed a new error type that uses a slice and thus cannot be compared without introducing a panic. We picked this change up through an update to blackfriday, but this could happen anywhere.

While I understand that this library is based on concepts of no longer using sentinel values, this is already a common practice in existing code. There is also limited ways for a caller to avoid the panic.

I suggest that errors with a slice value use a pointer to the error value to avoid this trap in the future. For example, instead of building a `stack{}`, use `&stack{}`. This will ensure that existing code can make error comparisons while new code can begin to adopt this great package.

**Comment by davecheney** [comment]
Thanks. I didn't consider that. I'll fix this immediately.

**Comment by stevvooe** [comment]
@davecheney Cheers!

I had never seen this either...

**Comment by stevvooe** [comment]
@davecheney Thanks for the quick fix!
