### ISSUE TITLE
Why implement errors.Errorf when we have fmt.Errorf?

### ISSUE THREAD

**Issue by matryer** [pkg/errors#31]
More of a package design question, but why have `errors.Errorf` when we [already have it in the fmt package](https://golang.org/pkg/fmt/#Errorf)?

Is it just so we have a single place for all our erroring needs or is it different in some non-obvious way?

**Comment by davecheney** [comment]
For convenience basically. You are correct that Errorf and Wrapf are
superfluous, but people fought hard to add them and I agree with their
rational.

Perhaps if this package is incorporated into go 1.8 errors.Errorf would be
surplus to requirements, but that's a debate for another day.

**Comment by matryer** [comment]
Thanks. Actually I love `Wrapf` and would miss it.
