### ISSUE TITLE
Helper to handle errors for the chain functions (that return errors).

### ISSUE THREAD

**Issue by msoap** [pkg/errors#4]
Example of helper function: https://github.com/msoap/shell2http/blob/master/shell2http.go#L430
Example of usage: https://github.com/msoap/shell2http/blob/master/shell2http.go#L409

If such a feature would be useful? I do PR

**Comment by davecheney** [comment]
Thank you for your request but this is not something I plan t add. If you wish you can fork this package and add the feature to your fork, it will continue to be compatible with errors.Cause as the only requirement is a `Cause() error` method.
