### ISSUE TITLE
MIT or BSD-2-clause?

### ISSUE THREAD

**Issue by anthonyfok** [pkg/errors#41]
I just noticed that:

* At the bottom of README.md, it says the license is **MIT**.
* However, the LICENSE file contains the **BSD-2-clause** license.

Thanks!

**Comment by davecheney** [comment]
The goal is to have a permissive licence for this package, I chose MIT when
I created the package via github's automated form.

I'm not a language lawyer. If you can suggest a fix I would be happy to
take a PR.

**Comment by anthonyfok** [comment]
Hi Dave,

> The goal is to have a permissive licence for this package, I chose MIT when
> I created the package via github's automated form.
>
> I'm not a language lawyer. If you can suggest a fix I would be happy to
> take a PR.

I would be happy to make a PR, but there are two possible but opposite solutions:

 1. Change `README.md` to say the licence is "BSD-2-clase".

 2. Replace the licence text in the `LICENSE` file with that of the MIT licence.  However, if we do this, github.com/pkg/errors and github.com/pkg/sftp would have different licences.  (The current `LICENSE` file  in github.com/pkg/sftp contains the text of the BSD-2-clause" licence.)

So, when you have time, could you please take a look at the following two licences:

* https://opensource.org/licenses/MIT
* https://opensource.org/licenses/BSD-2-Clause

and see which one you like better?  They are both very permissive licences.  :-)

(I was packaging pkg/errors for Debian as pkg/sftp now depends on it.  Debian's Go packaging helper `dh-make-golang` and friends rather intelligently determined the licence from the `LICENSE` file and automatically filled in the fields in the `debian/copyright` file, but then README.md says otherwise, so that's why I am here.  :smile:)

**Comment by davecheney** [comment]
The text in the LICENSE file is the authoritative copy, we cannot change
that.

**Comment by anthonyfok** [comment]
> The text in the LICENSE file is the authoritative copy, we cannot change that.

Thank you for the clarification!

Please see Pull Request #42 where the reference to "MIT" is changed to "BSD-2-Clause".

Cheers,
Anthony
