### ISSUE TITLE
Capitalise trace in Stacktrace

### ISSUE THREAD

**Issue by jongillham** [pkg/errors#50]
Have you considered changing `Stacktrace` to `StackTrace`? There are several examples on the internet where stacktrace is used as one word. However most examples seem to be [two separate words](https://en.wikipedia.org/wiki/Stack_trace) suggesting that the `Trace` should be capitalised. The Go runtime and debug packages mention stack trace as two separate words in documentation.

I know this is pedantic and opinionated so feel free to ignore.

**Comment by seh** [comment]
Related, in the documentation for the `+v` verb, [we find the word "Stacktrace"](https://github.com/pkg/errors/commit/9a4f977a0570cd26a97bdab0f50df0004983bb42#commitcomment-17835539).

**Comment by davecheney** [comment]
Good catch, I'll fix this before the 0.7 release.
