### ISSUE TITLE
goimports miss

### ISSUE THREAD

**Issue by powerman** [pkg/errors#62]
For many files it'll be enough to use just `errors.New()`, which result in goimports incorrectly import "errors" instead of "github.com/pkg/errors". This mistake will be hard to spot manually while code review and it'll show itself only when one of these errors will be output into log without stack trace.

Not sure is you can do anything with this - maybe just note this subtle trap in package documentation?

**Comment by davecheney** [comment]
I understand the problem, a similar problem exists with text/template and
html/template.

I'm not sure if documenting this would help, I don't even know where this
would go ? On the package, on the New method, in the github readme?

**Comment by powerman** [comment]
> on the New method

This is only affected method, so IMHO that's the place.

**Comment by davecheney** [comment]
I understand the problem, but there must be plenty of places where this happens in other code bases. 

It feels like overkill to have to document, or worse, avoid using a particular function name just because GoImports could lookup the wrong one by accident.

**Comment by davecheney** [comment]
But you're probably right that `errors.New` does have the potential to conflict, so if you want to take a crack at it, please do so. Please make it a brief as possible.

**Comment by benma** [comment]
I am using a custom built errors library very similar to this one, and my solution to the problem was to just name it something other than `errors`. I used `errp` (for "errors plus") to disambiguate, and it is also short and easy to type.

**Comment by mewmew** [comment]
Personally I would mark this as "unfortunate" and perhaps propagate the issue upstream to goimports. However, without additional context, I can't see what goimports may do better to resolve the issue. If `errors` is used in many places, and one of these places happen to be `errors.New`, while other places (obviously having `errors` refer to the same object of the same scope) refer to identifiers not exported in the stdlib `errors`, then this is an issue which `goimports` may solve.

In either case, adding documentation to `New` seems like attacking the problem from the wrong direction. At least from my point of view.

**Comment by davecheney** [comment]
I'm going to mark this closed as #62 is committed for better or worse

**Comment by mewmew** [comment]
> I'm going to mark this closed as #62 is committed for better or worse

As far as I can tell #65 was never merged, only closed.

**Comment by davecheney** [comment]
In that case the status is unfortunate. It's unfortunate, but I don't want to work around a tool with text.
