### ISSUE TITLE
Cause() is broken

### ISSUE THREAD

**Issue by tchap** [pkg/errors#67]
Hi,

Looking at the following code snippet:

```go
func Cause(err error) error {
	type causer interface {
		Cause() error
	}

	for err != nil {
		cause, ok := err.(causer)
		if !ok {
			break
		}
		err = cause.Cause()
	}
	return err
}
```

How is `err` ever going to be nil? I am getting `panic: interface conversion: error is errors.wrapper, not *net.OpError` after calling `errors.Cause`...

**Comment by davecheney** [comment]
Possibly your code is passing back a typed nil. Can you please provide some
sample code that shows the panic you get.

**Comment by tchap** [comment]
Let me think for a minute, 2:39am, I might be simply retarded :-)

**Comment by tchap** [comment]
Awww, ok, was looking at a wrong code line, forgot to wrap the thing in `Cause()` actually and type cast failed and panicked. Sorry for bothering you 👼

**Comment by davecheney** [comment]
Cool. Thanks for checking.
