### ISSUE TITLE
Expose Frame's pc, file, line and function name

### ISSUE THREAD

**Issue by pierrre** [pkg/errors#68]
Hello,

I'm currently writing a "bridge" for the Sentry Go library: https://github.com/getsentry/raven-go
I create a `StackTraceFrame` manually with https://godoc.org/github.com/getsentry/raven-go#NewStacktraceFrame
I need to be able to extract file/line information from a `Frame` https://godoc.org/github.com/pkg/errors#Frame

Could you add methods on a `Frame` to get:
- pc (by the way, I don't understand the "-1" logic)
- file
- line
- function name

Thank you

**Comment by captncraig** [comment]
In addition to just this, I have found the whole stack.go file to be really useful. Would you consider exporting the Callers function (with skipDepth as a parameter) so other packages can utilize the nice stack trace gathering / formatting code?

**Comment by ChrisHines** [comment]
The stack.go code came from my project at github.com/go-stack/stack. I
recommend you use that.

**Comment by sjhitchner** [comment]
Hi:

We're also trying to get a useful stack trace into Sentry.  Apart from parsing the output from a call to the Formatter how can we access the Stacktrace from the error?

**Comment by davecheney** [comment]
@sjhitchner StackTrace() returns a `[]errors.Frame`. That type has methods on it to inspect it. It can also be converted to a `uintptr` which is compatible with the `runtime.FuncForPC` class of helpers.

**Comment by pierrre** [comment]
@davecheney that's what I did, thank you.

**Comment by tj** [comment]
👍 this feels a bit obscure, and I'd love to have access to the filename alone, but it prepends the function name

**Comment by Julio-Guerra** [comment]
Exact same case happened to me: sending the stack trace to sentry.
And it's a shame we need to to rewrite those methods while they are actually implemented here.
