### ISSUE TITLE
Incorrect file returned by Location when vendored or in a different part of a multipart GOPATH.

### ISSUE THREAD

**Issue by ChrisHines** [pkg/errors#8]
To reproduce:

```
$ go get github.com/ChrisHines/pkg-errors-test
$ pkg-errors-test
ors-test.go:8: where am I?
```

To reproduce the multipart GOPATH scenario copy the pkg-errors-test repo to a different part of a mulitpart GOPATH from github.com/pkg/errors and delete the vendor folder. In that case you might see something like:

```
$ go run pkg-errors-test.go
hub.com/ChrisHines/pkg-errors-test/pkg-errors-test.go:8: where am I?
```

The exact output will depend on the path length delta between the two parts of the GOPATH.

I believe this can be fixed using a technique like what I have done here: https://github.com/go-stack/stack/blob/master/stack.go#L96.

I will work on a PR for this issue.

**Comment by davecheney** [comment]
Thank you. Please do.
