### ISSUE TITLE
[question] Recommendations for low-level pkgs not using github.com/pkg/errors

### ISSUE THREAD

**Issue by VojtechVitek** [pkg/errors#82]
RE: https://twitter.com/davecheney/status/758764120468357120 //cc @davecheney 

What is your recommendation for low-level pkgs that don't have (and likely won't ever have) any 3rd party dependencies, ie. DB drivers? Should they return errors of certain types satisfying behavior, ie. `_, ok := err.(db.ErrTemporary)`? Or do you have any other suggestions?

**Comment by davecheney** [comment]
yes. Writing an error type that implements temporary is only a few lines of code.

**Comment by VojtechVitek** [comment]
Thanks @davecheney!
