### ISSUE TITLE
Better stacks for caught panics

### ISSUE THREAD

**Issue by ethanfrey** [pkg/errors#92]
First of all, this is a great package and I am using it to good effect in my code, helping both my test and production errors become much more traceable.

However, there is one piece of polishing I was hoping for, and I don't know how to implement it cleanly.  I have an http server, and at the top level is a middleware, which catches panics and  returns a 500 Error and logs them (both to a file, and an error reporting service).  My middleware contains this for catching panics...

```
	defer func() {
		if rec := recover(); rec != nil {
			rest.ErrorHandler(rw, rec)  // this writes a custom 500 error 
			var wrap error
			if err, ok := rec.(error); ok {
				wrap = errors.Wrap(err, "Panic Handler")
			} else {
				wrap = errors.Errorf("%v", rec)
			}
			logger.WithError(wrap).Error(rec)
		}
	}()
```

And the error looks like this:

```
File "/home/jenkins/workspace/backend-tileserver-staging/src/panono/code/server/middleware/recovery.go" line 26 in middleware.recoveryMiddleware.ServeHTTP.func1
File "/usr/local/go16/src/runtime/asm_amd64.s" line 472 in runtime.call32
File "/usr/local/go16/src/runtime/panic.go" line 426 in runtime.gopanic
File "/home/jenkins/workspace/backend-tileserver-staging/src/panono/code/server/tileserver/tileserver.go" line 120 in tileserver.(*server).tileV5Handler
...
```

(Line 26 is the errors.Wrap line btw)

My wish would be to write something like:

```
if rec := recover(); rec != nil {
			rest.ErrorHandler(rw, rec)  // this writes a custom 500 error 
			wrap := errors.FromPanic(rec)
			logger.WithError(wrap).Error(rec)
		} 
```

and that the stack trace would start with the line that threw the panic. 
```
File "/home/jenkins/workspace/backend-tileserver-staging/src/panono/code/server/tileserver/tileserver.go" line 120 in tileserver.(*server).tileV5Handler
``` 

There is a line in `callers()` that gets the stack: `n := runtime.Callers(3, pcs[:])` Maybe this depth could be controlled by WithPanic to return `n := runtime.Callers(6, pcs[:])` in that case. But I am sure there are cleaner solutions.

I look forward to any feedback on this proposal.

**Comment by davecheney** [comment]
Thank you for opening this issue. 

I'm not sure I understand what you are asking. Are you asking for a way to turn a panic'd stack trace into an error?

**Comment by ethanfrey** [comment]
Yes, there are two parts:

One, when I create an error after recovering from a panic in a defer block, I would like an option to skip the first three calls (maybe just make this number an argument) from the stack trace, so it shows where the panic was thrown, not golang internals and where the panic was caught. As far as I understand, this involves changing internals of the errors package.

The second is more aesthetic.  To accept an interface (from recover) and wrap it if it is an error with no stack trace already, or create an error if it is a string.  This is easy enough to do in my own code, so maybe I will just remove that from this request.  Really, just adding a way to control how many calls to skip when generating a stack trace would be great.

**Comment by davecheney** [comment]
There are multiple requests for some kind of "add a stack trace only if
there isn't one already" in fly. The TLDR is figuring the logic for that
statement is complicated, which is why it isn't done yet.

As for manipulating a stack trace, that's outside the remit of this
package. Have a look at Chris Hines' stack paxkage.

**Comment by ethanfrey** [comment]
Nice point to the package. I guess I can do that with some helpers in my code.

I took a look at https://github.com/go-stack/stack/ and saw a `CallStack` type, with some nice manipulation methods.   I don't see an easy way to convert between stack.CallStack and  errors.StackTrace, but I can use the content of those methods for examples on how to manipulate the stack trace.

Thanks for the advice.
