### ISSUE TITLE
API Naming / consistency

### ISSUE THREAD

**Issue by hhrutter** [pkg/errors#95]
For creating errors we have:
```
func New(message string) error
func Errorf(format string, args ...interface{}) error
```

If instead we had 
```
func Error(args ...interface{}) error
func Errorf(format string, args ...interface{}) error
```
or
```
func New(args ...interface{}) error
func Newf(format string, args ...interface{}) error
```
we would go more along the lines of eg. the fmt package.

**Comment by davecheney** [comment]
1. I cannot rename the functions already in use, and adding extra ones is redundant.
2. errors.New was chosen to mimic the std library function of the same name.
3. errors.Errorf was chosen to mimick the fmt function of the same name, maybe it wasn't correct, but it's too late to change it now.

Thank you for your time.
