### ISSUE TITLE
frame.Format: %+s prints more than "path of source file relative to the compile time GOPATH"

### ISSUE THREAD

**Issue by judwhite** [pkg/errors#99]
Change: https://github.com/pkg/errors/commit/7896481a535a4ecd2e5507ed4c78902d9a58ef75?diff=unified#diff-7dc02266d93e96cde6ba279eadbcac8fR62
Doc: https://github.com/pkg/errors/blob/785921b1c1ecc027064eaf6616a7a01b4c292597/stack.go#L49

Changing back to `io.WriteString(s, trimGOPATH(fn.Name(), file))` gives the expected output.

This commit was merged 6 months ago; might break people to change it now. Would you accept a PR to put the previous behavior under `%#s` and an update to the documentation?

**Comment by judwhite** [comment]
@davecheney @ChrisHines Playing with this a little more I noticed `go vet` complains about `%n` (and `%#s`).

What do you think about exposing these values as methods on `Frame` with stronger guarantees than `Format`?

**Comment by davecheney** [comment]
> This commit was merged 6 months ago; might break people to change it now. Would you accept a PR to put the previous behavior under %#s and an update to the documentation?

It's probably too late to change the behaviour at this point. It'd be safer to document what exists now unless it's egregiously inconsistent.

**Comment by judwhite** [comment]
Current (248dadf):

```
func TestWrappedError(t *testing.T) {
	err := a()
	if st, ok := err.(stackTracer); ok {
		for _, frame := range st.StackTrace() {
			fmt.Printf("%+v\n", frame)
		}
	}
}

func a() error { return b() }
func b() error { return c() }
func c() error { return errors.Wrap(io.EOF, "unexpected eof") }
```

```
github.com/judwhite/httplog.c
        C:/Projects/go/src/github.com/judwhite/httplog/fallbackLogger_test.go:28
github.com/judwhite/httplog.b
        C:/Projects/go/src/github.com/judwhite/httplog/fallbackLogger_test.go:27
github.com/judwhite/httplog.a
        C:/Projects/go/src/github.com/judwhite/httplog/fallbackLogger_test.go:26
github.com/judwhite/httplog.TestWrappedError
        C:/Projects/go/src/github.com/judwhite/httplog/fallbackLogger_test.go:18
testing.tRunner
        C:/Go/src/testing/testing.go:610
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2086
```

Previous (d4b5735):

```
github.com/judwhite/httplog/fallbackLogger_test.go:30
github.com/judwhite/httplog/fallbackLogger_test.go:29
github.com/judwhite/httplog/fallbackLogger_test.go:28
github.com/judwhite/httplog/fallbackLogger_test.go:18
testing/testing.go:610
runtime/asm_amd64.s:2086
```

**Comment by judwhite** [comment]
I would be happy with a change like this:

```go
// FileName returns the path of the source file relative to the compile time GOPATH.
func (f Frame) FileName() string {
	pc := f.pc()
	fn := runtime.FuncForPC(pc)
	if fn == nil {
		return "unknown"
	}
	file, _ := fn.FileLine(pc)
	return trimGOPATH(fn.Name(), file)
}

// Function returns the function name.
func (f Frame) Function() string {
	name := runtime.FuncForPC(f.pc()).Name()
	return funcname(name)
}

// Line returns the source line.
func (f Frame) Line() int {
	return f.line()
}
```

If you're okay with this I'll submit a PR. The goal is to provide the user more control over stack trace formatting.

**Comment by ChrisHines** [comment]
Don't forget about #38. For reference see https://godoc.org/github.com/go-stack/stack#Call.Format and the code behind it.

**Comment by judwhite** [comment]
Closing.
